version: "2"
services:
  membersrvc:
    build:
      context: membersrvc
    command: membersrvc
    ports:
      - "7054:7054"
  vp0:
    image: hyperledger/fabric-peer:latest
    command: "sh -c 'while ! nc membersrvc 7054; do sleep 1; done; peer node start'"
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - "CORE_VM_ENDPOINT=unix:///var/run/docker.sock"
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=vp0
      - "CORE_PEER_PKI_ECA_PADDR=membersrvc:7054"
      - "CORE_PEER_PKI_TCA_PADDR=membersrvc:7054"
      - "CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054"
      - CORE_SECURITY_ENABLED=true
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
      - CORE_CHAINCODE_DEPLOYTIMEOUT=500000000
    links:
      - membersrvc
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7052:7052"
      - "7053:7053"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    links:
      - membersrvc
  vp1:
    image: hyperledger/fabric-peer:latest
    command: "sh -c 'while ! nc membersrvc 7054; do sleep 1; done; peer node start'"
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - "CORE_VM_ENDPOINT=unix:///var/run/docker.sock"
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=vp1
      - "CORE_PEER_PKI_ECA_PADDR=membersrvc:7054"
      - "CORE_PEER_PKI_TCA_PADDR=membersrvc:7054"
      - "CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054"
      - CORE_SECURITY_ENABLED=true
      - CORE_SECURITY_ENROLLID=test_vp2
      - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
    links:
      - vp0
      - membersrvc 
  vp2:
    image: hyperledger/fabric-peer:latest
    command: "sh -c 'while ! nc membersrvc 7054; do sleep 1; done; peer node start'"
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - "CORE_VM_ENDPOINT=unix:///var/run/docker.sock"
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=vp2
      - "CORE_PEER_PKI_ECA_PADDR=membersrvc:7054"
      - "CORE_PEER_PKI_TCA_PADDR=membersrvc:7054"
      - "CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054"
      - CORE_SECURITY_ENABLED=true
      - CORE_SECURITY_ENROLLID=test_vp1
      - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
    links:
      - vp0
      - membersrvc
  vp3:
    image: hyperledger/fabric-peer:latest
    command: "sh -c 'while ! nc membersrvc 7054; do sleep 1; done; peer node start'"
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - "CORE_VM_ENDPOINT=unix:///var/run/docker.sock"
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=vp3
      - "CORE_PEER_PKI_ECA_PADDR=membersrvc:7054"
      - "CORE_PEER_PKI_TCA_PADDR=membersrvc:7054"
      - "CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054"
      - CORE_SECURITY_ENABLED=true
      - CORE_SECURITY_ENROLLID=test_vp3
      - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
    links:
      - vp0
      - membersrvc